/**
 * @namespace CopilotKitRoute
 * @module src/app/api/copilotkit/route.ts
 * @author ssdeanx
 * @version 1.0.0
 * @license MIT
 * @see {@link https://docs.copilotkit.ai/guides/self-hosting|CopilotKit Self-Hosting Guide}
 * @see {@link https://docs.mastra.ai/|Mastra Documentation}
 * @see {@link https://github.com/ssdeanx/coagents-mastra|GitHub Repository}
 * @file This file sets up the CopilotKit runtime for Next.js, allowing it to handle requests
 * and interact with the Mastra backend. It initializes the runtime with agents,
 * sets up the service adapter, and provides endpoints for handling POST and GET requests.
 * The runtime is configured to use the Mastra client for agent management and telemetry/logging.
 * The `initRuntime` function is called to set up the runtime environment, ensuring that
 * the CopilotKit runtime is properly configured and ready to handle requests.
 *
 * @implements The CopilotKit Self-Hosting Guide
 * @implements The Mastra Documentation
 * @implements The GitHub Repository
 * @since 2025-07-17 11:34AM eST
 */

import { NextRequest } from "next/server";
import {
  CopilotRuntime,
  ExperimentalEmptyAdapter,
  copilotRuntimeNextJSAppRouterEndpoint,
} from "@copilotkit/runtime";
import { MastraAgent } from "@ag-ui/mastra";
import { MastraClient } from "@mastra/client-js";
import type { AbstractAgent } from "@ag-ui/client";

// TypeScript interfaces for telemetry data
interface TelemetryData {
  name?: string;
  scope?: string;
  traces?: unknown[];
  metrics?: Record<string, unknown>;
  [key: string]: unknown;
}

interface LogData {
  transportId?: string;
  level?: string;
  message?: string;
  timestamp?: string;
  [key: string]: unknown;
}



// Extend global interface for telemetry data storage
declare global {
// sourcery skip: avoid-using-var
  var mastraTelemetry: TelemetryData | undefined;
  var mastraLogs: LogData[] | undefined;
  var mastraAgents: Record<string, AbstractAgent> | undefined;
}

// 1. Base address for the Mastra server
const MASTRA_URL = process.env.MASTRA_URL ?? "http://localhost:4111";


// Common init logic moved to top‐level
/**
 * Initializes the CopilotKit runtime environment for handling API requests.
 *
 * This function sets up the Mastra client, loads remote agents, configures the CopilotKit runtime,
 * and prepares the Next.js API endpoint for request handling and debugging.
 *
 * Args:
 *   None
 * Returns:
 *   A configured Next.js API endpoint handler for CopilotKit requests.
 */
async function initRuntime() {
  const client = new MastraClient({ baseUrl: MASTRA_URL });
  const serviceAdapter = new ExperimentalEmptyAdapter();
  const remoteAgents = await MastraAgent.getRemoteAgents({ mastraClient: client });
  const runtime = new CopilotRuntime({
    agents: remoteAgents as unknown as Record<string, AbstractAgent>,
  });

  // Fetch telemetry/logs for real-time monitoring and agent management
  const telemetry = await client.getTelemetry({ name: "trace-name", scope: "scope-name", page: 1, perPage: 10, attribute: { key: "value" } });
  console.log("Fetched telemetry:", telemetry);
  const logs = await client.getLogs({ transportId: "transport-1" });
  console.log("Fetched logs:", logs);

  // Store telemetry and logs data for frontend access
  global.mastraTelemetry = telemetry as unknown as TelemetryData;
  global.mastraLogs = logs as unknown as LogData[];
  global.mastraAgents = remoteAgents;

  return copilotRuntimeNextJSAppRouterEndpoint({
    runtime,
    serviceAdapter,
    endpoint: "/api/copilotkit",
  });
}

/**
 * Handles POST requests to the CopilotKit API endpoint.
 *
 * This function receives a Next.js request, initializes the CopilotKit runtime, and delegates the request to the runtime handler.
 * It also supports a special query parameter 'telemetry=true' to return the real telemetry and logs data.
 *
 * Args:
 *   req: The incoming Next.js request object.
 * Returns:
 *   The response generated by the CopilotKit runtime handler, or telemetry data if requested.
 */
export async function POST(req: NextRequest) {
  const url = new URL(req.url);

  // Check if telemetry data is requested
  if (url.searchParams.get('telemetry') === 'true') {
    try {
      // Initialize runtime to ensure telemetry data is fetched and stored in global variables
      await initRuntime();

      // Return the real telemetry and logs data that was fetched and stored
      return new Response(JSON.stringify({
        success: true,
        timestamp: new Date().toISOString(),
        data: {
          telemetry: global.mastraTelemetry,
          logs: global.mastraLogs,
          agents: global.mastraAgents
        }
      }), {
        headers: { 'Content-Type': 'application/json' }
      });
    } catch (err) {
      console.error('Telemetry fetch error:', err);
      return new Response(JSON.stringify({
        success: false,
        error: 'Failed to fetch telemetry data from Mastra backend',
        details: err instanceof Error ? err.message : 'Unknown error',
        timestamp: new Date().toISOString()
      }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' }
      });
    }
  }

  // Default CopilotKit behavior
  const { handleRequest } = await initRuntime();
  return handleRequest(req);
}
// If you also need GET support, simply forward to POST
/**
 * Handles GET requests to the CopilotKit API endpoint.
 *
 * This function receives a Next.js request, initializes the CopilotKit runtime, and delegates the request to the runtime handler.
 * It also supports a special query parameter 'telemetry=true' to return the real telemetry and logs data.
 *
 * Args:
 *   req: The incoming Next.js request object.
 * Returns:
 *   The response generated by the CopilotKit runtime handler, or telemetry data if requested.
 */
export async function GET(req: NextRequest) {
  const url = new URL(req.url);

  // Check if telemetry data is requested
  if (url.searchParams.get('telemetry') === 'true') {
    try {
      // Initialize runtime to ensure telemetry data is fetched
      await initRuntime();

      // Return the real telemetry and logs data that was fetched
      return new Response(JSON.stringify({
        success: true,
        timestamp: new Date().toISOString(),
        data: {
          telemetry: global.mastraTelemetry,
          logs: global.mastraLogs,
          agents: global.mastraAgents
        }
      }), {
        headers: { 'Content-Type': 'application/json' }
      });
    } catch (err) {
      console.error('Telemetry fetch error:', err);
      return new Response(JSON.stringify({
        success: false,
        error: 'Failed to fetch telemetry data from Mastra backend',
        details: err instanceof Error ? err.message : 'Unknown error',
        timestamp: new Date().toISOString()
      }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' }
      });
    }
  }

  // Default CopilotKit behavior
  const { handleRequest } = await initRuntime();
  return handleRequest(req);
}
// Configuration for Next.js Edge Runtime
export const config = {
  runtime: "edge",
};

/*
 * This file sets up the CopilotKit runtime for Next.js, allowing it to handle requests
 * and interact with the Mastra backend. It initializes the runtime with agents,
 * sets up the service adapter, and provides endpoints for handling POST and GET requests.
 * The runtime is configured to use the Mastra client for agent management and telemetry/logging.
 * The `initRuntime` function is called to set up the runtime environment, ensuring that
 * the CopilotKit runtime is properly configured and ready to handle requests.
 *
 * @see {@link https://docs.copilotkit.ai/guides/self-hosting|CopilotKit Self-Hosting Guide}
 * @see {@link https://docs.mastra.ai/|Mastra Documentation}
 * @see {@link https://github.com/ssdeanx/coagents-mastra|GitHub Repository}
 */